name: Docker Image CI (Build)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build_and_push_image:
    # Only build / publish the image on the main branch and not for pull requests.
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    # From official documentation of build-push-action:
    # https://github.com/marketplace/actions/build-and-push-docker-images
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64/v8
          push: true
          tags: denisgolubev/robots-txt-extender:latest
